// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace Entity;

[Table("VEHICULE")]
[Index("Immatriculation", Name = "UQ__VEHICULE__3548AE3EC43DD606", IsUnique = true)]
public partial class Vehicule
{
    [Key]
    [Column("ID")]
    public int Id { get; set; }

    [Required]
    [Column("IMMATRICULATION")]
    [StringLength(50)]
    public string Immatriculation { get; set; }

    [Required]
    [Column("MODELE")]
    [StringLength(100)]
    [Unicode(false)]
    public string Modele { get; set; }

    [Required]
    [Column("COULEUR")]
    [StringLength(50)]
    public string Couleur { get; set; }

    [Column("ID_MARQUE")]
    public int? IdMarque { get; set; }

    [Column("ID_CATEGORIE")]
    public int? IdCategorie { get; set; }

    [ForeignKey("IdCategorie")]
    [InverseProperty("Vehicules")]
    public virtual Categorie IdCategorieNavigation { get; set; }

    [ForeignKey("IdMarque")]
    [InverseProperty("Vehicules")]
    public virtual Marque IdMarqueNavigation { get; set; }

    [InverseProperty("IdVehiculeNavigation")]
    public virtual ICollection<Location> Locations { get; set; } = new List<Location>();
}